import multiprocessing
NUM_CPUS = multiprocessing.cpu_count()
ORIGIN_HEIGHT = 1024

MIN_NUM_VOTES = 50
NON_MAX_SUP_RANGE = 32
NUM_HOUGH_LINES = 20

MIN_AREA_RATIO = 0.20
NUM_CANDIDATE_VERTICES = 64

EXPAND_PIXEL = 2
